# config.yaml - Configuration for Snakemake pipeline

# General pipeline configuration
trait: Celiac # Trait of interest
icd_count: -1 # Number of ICD codes needed to classify as a case, if -1, all cases will be included
results_dir: results/lr_celiac_1000 # Results directory
data_dir: data # Data directory
output_prefix: celiac_1000 # Output prefix
n_permute: 10000 # Number of permutations for phecode enrichment analysis, increase for more accurate p-value
model_type: LR # Model type, choose from CART, RF, XG, NN/MLP, LR, LSVC, SVC, or RC
use_matched_controls: 1 # Whether to use matched controls for ML, 1 for yes, 0 for no
n_controls_per_case: 4 # Number of controls to use per case
train_split_ratio: 0.8 # Proportion of matched pairs allocated to the training split
min_phecode_frequency: 0 # Minimum frequency of a phecode to be included as a feature
feature_selection_method: enrichment # Feature selection method, choose from enrichment or phewas
kernel: poly #kernel to use if the model is SVC
excluded_codes: # List of ICD codes and Phecodes to exclude from the ML pipeline (these are typically used for phenotyping)
  ICD:
    # - '307.1'
    # - 'F50.00'
    # - 'F50.01'
    # - 'F50.02'
    #- '307.0' #stuttering
  Phecode:
    # - '305.21'
    # - '305.2'
    #- '313.2' #tics and stuttering

# Data file paths (project agnostic)
phecode_binary_file: /data100t1/share/synthetic-deriv/phecodes/all-sd-phecodes-mar-2025/sd_samples_phecode.binary.txt.gz
phecode_binary_feather_file: /data100t1/share/synthetic-deriv/phecodes/all-sd-phecodes-mar-2025/sd_samples_phecode.binary.feather
phecode_map_file: /data100t1/share/synthetic-deriv/phecodes/ICD_Phecode_mapping.csv # Map between ICD codes and Phecodes and corresponding Phecode strings
demographics_file: /data100t1/share/synthetic-deriv/demographic-releases/2025-mar-19/sd_demographics.csv.gz

# Stuttering
#case_path: /data100t1/share/stuttering/SexSpecificStutteringML/cases_2022.txt
#control_exclusion_list:
#depth_of_record_path: /data100t1/share/synthetic-deriv/phecodes/all-sd-phecodes-mar-2025/depth_of_record_in_sd.csv

# HPP project
# hpp_case_path: /data100t1/home/wanying/BioVU/202505_hypophosphatasia/data/hpp_icd_code_counts_in_sd.case_only.csv
# hpp_control_exclusion_list: /data100t1/home/biand/Projects/PheWES/data/celiac_GRIDs_not_controls.txt
# hpp_depth_of_record_path: /data100t1/share/synthetic-deriv/phecodes/all-sd-phecodes-mar-2025/depth_of_record_in_sd.csv

# Celiac project
#phecode_binary_file: /data100t1/home/biand/Projects/Celiac_Project/data/phecode_before_positive_1113.csv.gz
#phecode_binary_feather_file: /data100t1/home/biand/Projects/Celiac_Project/data/binary_phecode_1113.feather
case_path: /data100t1/home/emerson/PheMINE/celiac_cases_manual_review.txt
control_exclusion_list: /data100t1/home/emerson/PheMINE/celiac_control_exclusion_grids.txt
depth_of_record_path: /data100t1/home/biand/Projects/Celiac_Project/data/grid_depth_1113.csv

# AN
# phecode_binary_feather_file: /data100t1/home/biand/Projects/PheWES/results/an_0130/binary_phecode.feather

# Example data paths (for testing or demonstration purposes), uncomment the following lines to use the example data
#phecode_map_file: data/sample_data/ICD_Phecode_mapping.csv
#demographics_file: data/sample_data/demographics.csv
#phecode_binary_feather_file: data/sample_data/phecode_binary.feather
#case_path: data/sample_data/cases.csv
#control_exclusion_list: data/sample_data/excluded_controls.txt
#depth_of_record_path: data/sample_data/depth_of_record.csv
